//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EUUI MVC Extension - IController 集成
// </auto-generated>
//------------------------------------------------------------------------------
namespace Game.UI
{
    /// <summary>
    /// MVC 架构集成（分部类）
    /// GetModel/GetSystem/SendCommand 等方法由 IController 扩展自动提供
    /// </summary>
    public partial class WndTestPanel : EUFramework.Core.MVC.Interface.IController
    {
        
    }
}
