//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EUUI Code Generator.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using EUFramework.Core.MVC.Interface;

namespace Game.UI
{
    public partial class WndTestPanel
    {
        [Header("Auto Generated Bindings")]
        [SerializeField] public UnityEngine.UI.Image Image;
    }

    public partial class WndTestPanel : IController
    {

    }
}
